development:
    adapter: sqlite3
    database: db/development.sqlite3
    host: localhost

production:
    adapter: postgresql
    database: development
    username: <%= ENV['PG_USER'] %>
    password: <%= ENV['PG_PASS'] %>
    host: localhost
